### ISSUE TITLE
Does this work with .scss and url()?

### ISSUE THREAD

**Issue by alexandernst** [RobinCK/alias-resolve-loader#1]
I have a `.scss` file and I'm trying to use an image as a background (`background-image: url('@app/foo/bar.png')`). Will this module work for that?

**Comment by RobinCK** [comment]
Hi @alexandernst 

Should work.
At least I checked for less.

Show your webpack configuration

**Comment by alexandernst** [comment]
Ok, yes, it works, but there is a bug in your other library. Let me open an issue there ;)
